### ISSUE TITLE
Reversing order shouldn't update time

### ISSUE THREAD

**Issue by haltman-at** [bakkot/SlateStarComments#10]
Hi,

So, I noticed the new reverse comment order button; it's quite useful!  However, it updates the comment time, which (like logging in) it shouldn't do -- reversing the comment order should keep the same comments highlighted.  Could this be fixed?

Thank you!

**Comment by bakkot** [comment]
Hadn't seen that, neat! Should be fixed by f2b1ea5925d347fcdf6b80a5da52de5401986dd8, though it may take ten or twenty minutes before your browser picks up the new script.

Thanks for the report!

**Comment by haltman-at** [comment]
Thanks!
