### ISSUE TITLE
Wrap hider and scroll-to-comment links in <a> elements

### ISSUE THREAD

**Issue by roryokane** [bakkot/SlateStarComments#2]
That way, the cursor would turn into a pointer when it hovers over those links. Currently, it feels weird that those links have an action when clicked, yet the cursor stays the same. Using actual `<a>` elements for the links would probably have accessibility benefits too.

The `href` of each `a` element should be `javascript:`. That value makes the link valid, and doesn’t need any extra code to change its scroll behavior, unlike the value `#`.

**Comment by bakkot** [comment]
Styled with  `cursor: pointer` instead, which achieves approximately the same effect.
