### ISSUE TITLE
New-comments box covers blog content

### ISSUE THREAD

**Issue by jruderman** [bakkot/SlateStarComments#5]
At high zoom levels, `.comments-floater` covers some of the blog post I'm trying to read. Can you change it to not be `position: fixed`, or restrict it to covering part of the sidebar?

**Comment by bakkot** [comment]
Not readily. The overwhelming majority of users do not mess with the zoom level, and it works well for them; both of the fixes you propose, and any others I can think of, would interfere with their UX. In particular, it's ok (I feel) for it to cover up a part of the blog content when the window is thin, but not zoomed.

That said, [here](https://gist.github.com/bakkot/375f1d1cc07d69181d9e)'s a bookmarklet you can run to cause the floater to be in a fixed position. I might make it possible to make this persistent at some point (by running something in the console), if enough people have this issue.
